name: flutter_gdscmaliki
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  firebase: ^9.0.3
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  google_sign_in: ^5.4.2
  cloud_firestore: ^3.5.1
  path_provider: ^2.0.11
  dio: ^4.0.6
  animated_splash_screen: ^1.3.0
  flutter_screenutil: ^5.5.4
  wc_form_validators: ^1.0.0
  select_form_field: ^2.2.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
